spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8181/realms/Social-media-microservices
          jwk-set-uri:
            http://localhost:8181/realms/Social-media-microservices/protocol/openid-connect/certs

  application:
    name: api-gateway



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true


server:
  port: 8082


logging:
  level:
    org.springframework.cloud.gateway.route.CachingRouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
    root: INFO


